#pragma once

#include "arrangrr/arranger/style_model.hpp"

namespace arrangrr {
namespace styles {


// ---------------------------------------------------------------------------
// "motown": soul backbeat — kick 1 & 3, cracking snare 2 & 4, tambourine on the
// eighths, a melodic eighth-note soul bass line and bright off-beat triad stabs.
namespace motown {
inline constexpr StyleEvent kHeldBass[] = {{.step=0, .tone=kRoot, .octave=0, .vel=94, .gate=kGateHeld}};
inline constexpr StyleEvent kSoulBass[] = {{.step=0, .tone=kRoot, .octave=0, .vel=100, .gate=kGate8th}, {.step=4, .tone=kThird, .octave=0, .vel=88, .gate=kGate8th}, {.step=6, .tone=kFifth, .octave=0, .vel=84, .gate=kGate8th}, {.step=8, .tone=kFifth, .octave=0, .vel=94, .gate=kGate8th}, {.step=10, .tone=kRoot, .octave=1, .vel=86, .gate=kGate8th}, {.step=12, .tone=kThird, .octave=0, .vel=90, .gate=kGate8th}, {.step=14, .tone=kSeventh, .octave=0, .vel=84, .gate=kGate8th}};
inline constexpr StyleEvent kIn1D[] = {{.step=8, .tone=kTambourine, .octave=0, .vel=58, .gate=50}, {.step=10, .tone=kTambourine, .octave=0, .vel=64, .gate=50}, {.step=12, .tone=kSnare, .octave=0, .vel=80, .gate=100}, {.step=14, .tone=kSnare, .octave=0, .vel=92, .gate=100}};
inline constexpr StylePattern kIn1P[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kIn1D)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kHeldBass)}};
inline constexpr StyleEvent kIn2D[] = {{.step=0, .tone=kKick, .octave=0, .vel=100, .gate=120}, {.step=8, .tone=kKick, .octave=0, .vel=96, .gate=120}, {.step=4, .tone=kSnare, .octave=0, .vel=98, .gate=120}, {.step=12, .tone=kSnare, .octave=0, .vel=98, .gate=120}, {.step=0, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=2, .tone=kTambourine, .octave=0, .vel=54, .gate=50}, {.step=4, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=6, .tone=kTambourine, .octave=0, .vel=54, .gate=50}, {.step=8, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=10, .tone=kTambourine, .octave=0, .vel=54, .gate=50}, {.step=12, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=14, .tone=kTambourine, .octave=0, .vel=54, .gate=50}};
inline constexpr StyleEvent kIn2C[] = {{.step=2, .tone=kRoot, .octave=0, .vel=78, .gate=kGateStab}, {.step=2, .tone=kThird, .octave=0, .vel=78, .gate=kGateStab}, {.step=2, .tone=kFifth, .octave=0, .vel=78, .gate=kGateStab}, {.step=10, .tone=kRoot, .octave=0, .vel=76, .gate=kGateStab}, {.step=10, .tone=kThird, .octave=0, .vel=76, .gate=kGateStab}, {.step=10, .tone=kFifth, .octave=0, .vel=76, .gate=kGateStab}};
inline constexpr StylePattern kIn2P[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kIn2D)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSoulBass)}, {.role=TrackRole::kChord1, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kIn2C)}};
inline constexpr StyleEvent kAD[] = {
    {.step=0, .tone=kKick, .octave=0, .vel=106, .gate=120}, {.step=8, .tone=kKick, .octave=0, .vel=102, .gate=120}, {.step=4, .tone=kSnare, .octave=0, .vel=108, .gate=120}, {.step=12, .tone=kSnare, .octave=0, .vel=108, .gate=120},
    {.step=0, .tone=kTambourine, .octave=0, .vel=64, .gate=50}, {.step=2, .tone=kTambourine, .octave=0, .vel=56, .gate=50}, {.step=4, .tone=kTambourine, .octave=0, .vel=64, .gate=50}, {.step=6, .tone=kTambourine, .octave=0, .vel=56, .gate=50}, {.step=8, .tone=kTambourine, .octave=0, .vel=64, .gate=50}, {.step=10, .tone=kTambourine, .octave=0, .vel=56, .gate=50}, {.step=12, .tone=kTambourine, .octave=0, .vel=64, .gate=50}, {.step=14, .tone=kTambourine, .octave=0, .vel=56, .gate=50},
};
inline constexpr StyleEvent kAC[] = {{.step=2, .tone=kRoot, .octave=0, .vel=82, .gate=kGateStab}, {.step=2, .tone=kThird, .octave=0, .vel=82, .gate=kGateStab}, {.step=2, .tone=kFifth, .octave=0, .vel=82, .gate=kGateStab}, {.step=6, .tone=kRoot, .octave=0, .vel=78, .gate=kGateStab}, {.step=6, .tone=kThird, .octave=0, .vel=78, .gate=kGateStab}, {.step=6, .tone=kFifth, .octave=0, .vel=78, .gate=kGateStab}, {.step=10, .tone=kRoot, .octave=0, .vel=82, .gate=kGateStab}, {.step=10, .tone=kThird, .octave=0, .vel=82, .gate=kGateStab}, {.step=10, .tone=kFifth, .octave=0, .vel=82, .gate=kGateStab}, {.step=14, .tone=kRoot, .octave=0, .vel=78, .gate=kGateStab}, {.step=14, .tone=kThird, .octave=0, .vel=78, .gate=kGateStab}, {.step=14, .tone=kFifth, .octave=0, .vel=78, .gate=kGateStab}};
inline constexpr StylePattern kAP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kAD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSoulBass)}, {.role=TrackRole::kChord1, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kAC)}};
inline constexpr StyleEvent kBD[] = {
    {.step=0, .tone=kKick, .octave=0, .vel=108, .gate=120}, {.step=6, .tone=kKick, .octave=0, .vel=90, .gate=120}, {.step=8, .tone=kKick, .octave=0, .vel=104, .gate=120}, {.step=4, .tone=kSnare, .octave=0, .vel=110, .gate=120}, {.step=12, .tone=kSnare, .octave=0, .vel=110, .gate=120}, {.step=10, .tone=kSnare, .octave=0, .vel=58, .gate=50},
    {.step=0, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=1, .tone=kTambourine, .octave=0, .vel=52, .gate=50}, {.step=2, .tone=kTambourine, .octave=0, .vel=58, .gate=50}, {.step=3, .tone=kTambourine, .octave=0, .vel=52, .gate=50}, {.step=4, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=5, .tone=kTambourine, .octave=0, .vel=52, .gate=50}, {.step=6, .tone=kTambourine, .octave=0, .vel=58, .gate=50}, {.step=7, .tone=kTambourine, .octave=0, .vel=52, .gate=50}, {.step=8, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=9, .tone=kTambourine, .octave=0, .vel=52, .gate=50}, {.step=10, .tone=kTambourine, .octave=0, .vel=58, .gate=50}, {.step=11, .tone=kTambourine, .octave=0, .vel=52, .gate=50}, {.step=12, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=13, .tone=kTambourine, .octave=0, .vel=52, .gate=50}, {.step=14, .tone=kTambourine, .octave=0, .vel=58, .gate=50}, {.step=15, .tone=kTambourine, .octave=0, .vel=52, .gate=50},
};
inline constexpr StyleEvent kBC[] = {{.step=2, .tone=kRoot, .octave=0, .vel=84, .gate=kGateStab}, {.step=2, .tone=kThird, .octave=0, .vel=84, .gate=kGateStab}, {.step=2, .tone=kFifth, .octave=0, .vel=84, .gate=kGateStab}, {.step=2, .tone=kSeventh, .octave=0, .vel=84, .gate=kGateStab}, {.step=6, .tone=kRoot, .octave=0, .vel=80, .gate=kGateStab}, {.step=6, .tone=kThird, .octave=0, .vel=80, .gate=kGateStab}, {.step=6, .tone=kFifth, .octave=0, .vel=80, .gate=kGateStab}, {.step=8, .tone=kThird, .octave=0, .vel=76, .gate=kGateStaccato}, {.step=8, .tone=kFifth, .octave=0, .vel=76, .gate=kGateStaccato}, {.step=10, .tone=kRoot, .octave=0, .vel=84, .gate=kGateStab}, {.step=10, .tone=kThird, .octave=0, .vel=84, .gate=kGateStab}, {.step=10, .tone=kFifth, .octave=0, .vel=84, .gate=kGateStab}, {.step=10, .tone=kSeventh, .octave=0, .vel=84, .gate=kGateStab}, {.step=14, .tone=kRoot, .octave=0, .vel=80, .gate=kGateStab}, {.step=14, .tone=kThird, .octave=0, .vel=80, .gate=kGateStab}, {.step=14, .tone=kFifth, .octave=0, .vel=80, .gate=kGateStab}};
inline constexpr StylePattern kBP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kBD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSoulBass)}, {.role=TrackRole::kChord1, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kBC)}};
inline constexpr StyleEvent kFAD[] = {{.step=0, .tone=kKick, .octave=0, .vel=104, .gate=120}, {.step=4, .tone=kSnare, .octave=0, .vel=100, .gate=120}, {.step=8, .tone=kSnare, .octave=0, .vel=92, .gate=120}, {.step=10, .tone=kSnare, .octave=0, .vel=96, .gate=120}, {.step=12, .tone=kSnare, .octave=0, .vel=104, .gate=120}, {.step=14, .tone=kSnare, .octave=0, .vel=110, .gate=120}};
inline constexpr StyleEvent kFBD[] = {{.step=0, .tone=kKick, .octave=0, .vel=104, .gate=120}, {.step=4, .tone=kSnare, .octave=0, .vel=98, .gate=100}, {.step=6, .tone=kSnare, .octave=0, .vel=92, .gate=100}, {.step=8, .tone=kTomHi, .octave=0, .vel=96, .gate=100}, {.step=10, .tone=kTomMid, .octave=0, .vel=100, .gate=100}, {.step=12, .tone=kTomLow, .octave=0, .vel=104, .gate=100}, {.step=14, .tone=kTomFloor, .octave=0, .vel=110, .gate=100}};
inline constexpr StyleEvent kFCD[] = {{.step=0, .tone=kSnare, .octave=0, .vel=94, .gate=100}, {.step=2, .tone=kSnare, .octave=0, .vel=88, .gate=100}, {.step=4, .tone=kTomHi, .octave=0, .vel=98, .gate=100}, {.step=6, .tone=kTomHi, .octave=0, .vel=94, .gate=100}, {.step=8, .tone=kTomMid, .octave=0, .vel=102, .gate=100}, {.step=10, .tone=kTomMid, .octave=0, .vel=98, .gate=100}, {.step=12, .tone=kTomLow, .octave=0, .vel=108, .gate=100}, {.step=14, .tone=kTomFloor, .octave=0, .vel=114, .gate=100}};
inline constexpr StyleEvent kFDD[] = {{.step=0, .tone=kSnare, .octave=0, .vel=92, .gate=50}, {.step=1, .tone=kSnare, .octave=0, .vel=86, .gate=50}, {.step=2, .tone=kSnare, .octave=0, .vel=96, .gate=50}, {.step=3, .tone=kSnare, .octave=0, .vel=90, .gate=50}, {.step=4, .tone=kTomHi, .octave=0, .vel=100, .gate=50}, {.step=6, .tone=kTomHi, .octave=0, .vel=96, .gate=50}, {.step=8, .tone=kTomMid, .octave=0, .vel=104, .gate=50}, {.step=10, .tone=kTomLow, .octave=0, .vel=108, .gate=50}, {.step=12, .tone=kTomFloor, .octave=0, .vel=112, .gate=50}, {.step=13, .tone=kSnare, .octave=0, .vel=114, .gate=50}, {.step=14, .tone=kSnare, .octave=0, .vel=118, .gate=50}, {.step=15, .tone=kCrash, .octave=0, .vel=120, .gate=kGate8th}};
inline constexpr StylePattern kFAP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kFAD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSoulBass)}};
inline constexpr StylePattern kFBP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kFBD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSoulBass)}};
inline constexpr StylePattern kFCP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kFCD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSoulBass)}};
inline constexpr StylePattern kFDP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kFDD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSoulBass)}};
inline constexpr StyleEvent kE1D[] = {{.step=0, .tone=kKick, .octave=0, .vel=106, .gate=120}, {.step=0, .tone=kCrash, .octave=0, .vel=100, .gate=kGateHalfBar}};
inline constexpr StyleEvent kE1B[] = {{.step=0, .tone=kRoot, .octave=0, .vel=98, .gate=kGateHeld}};
inline constexpr StyleEvent kE1C[] = {{.step=0, .tone=kRoot, .octave=0, .vel=84, .gate=kGateHeld}, {.step=0, .tone=kThird, .octave=0, .vel=84, .gate=kGateHeld}, {.step=0, .tone=kFifth, .octave=0, .vel=84, .gate=kGateHeld}};
inline constexpr StylePattern kE1P[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kE1D)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kE1B)}, {.role=TrackRole::kChord1, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kE1C)}};
inline constexpr StyleEvent kE2D[] = {{.step=0, .tone=kCrash, .octave=0, .vel=110, .gate=kGateHeld}, {.step=0, .tone=kKick, .octave=0, .vel=108, .gate=120}, {.step=8, .tone=kKick, .octave=0, .vel=100, .gate=120}, {.step=12, .tone=kSnare, .octave=0, .vel=104, .gate=120}};
inline constexpr StyleEvent kE2B[] = {{.step=0, .tone=kRoot, .octave=-1, .vel=104, .gate=kGateHeld}, {.step=0, .tone=kRoot, .octave=0, .vel=94, .gate=kGateHeld}};
inline constexpr StyleEvent kE2C[] = {{.step=0, .tone=kRoot, .octave=0, .vel=86, .gate=kGateHeld}, {.step=0, .tone=kThird, .octave=0, .vel=86, .gate=kGateHeld}, {.step=0, .tone=kFifth, .octave=0, .vel=86, .gate=kGateHeld}, {.step=0, .tone=kSeventh, .octave=0, .vel=86, .gate=kGateHeld}};
inline constexpr StylePattern kE2P[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kE2D)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kE2B)}, {.role=TrackRole::kChord1, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kE2C)}};
// varC: half-time soul — backbeat on beat 3, tambourine eighths, sustained triad.
inline constexpr StyleEvent kCD[] = {{.step=0, .tone=kKick, .octave=0, .vel=106, .gate=120}, {.step=8, .tone=kSnare, .octave=0, .vel=108, .gate=120}, {.step=0, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=2, .tone=kTambourine, .octave=0, .vel=54, .gate=50}, {.step=4, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=6, .tone=kTambourine, .octave=0, .vel=54, .gate=50}, {.step=8, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=10, .tone=kTambourine, .octave=0, .vel=54, .gate=50}, {.step=12, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=14, .tone=kTambourine, .octave=0, .vel=54, .gate=50}};
inline constexpr StyleEvent kCC[] = {{.step=0, .tone=kRoot, .octave=0, .vel=78, .gate=kGateBeat}, {.step=0, .tone=kThird, .octave=0, .vel=78, .gate=kGateBeat}, {.step=0, .tone=kFifth, .octave=0, .vel=78, .gate=kGateBeat}, {.step=8, .tone=kRoot, .octave=0, .vel=76, .gate=kGateBeat}, {.step=8, .tone=kThird, .octave=0, .vel=76, .gate=kGateBeat}, {.step=8, .tone=kFifth, .octave=0, .vel=76, .gate=kGateBeat}};
inline constexpr StylePattern kCP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kCD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSoulBass)}, {.role=TrackRole::kChord1, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kCC)}};
// varD: peak soul — kick pushes, cracking snare with ghost, 16th tambourine, full 7th stabs.
inline constexpr StyleEvent kDD[] = {{.step=0, .tone=kKick, .octave=0, .vel=108, .gate=120}, {.step=6, .tone=kKick, .octave=0, .vel=90, .gate=120}, {.step=8, .tone=kKick, .octave=0, .vel=104, .gate=120}, {.step=10, .tone=kKick, .octave=0, .vel=88, .gate=120}, {.step=4, .tone=kSnare, .octave=0, .vel=112, .gate=120}, {.step=12, .tone=kSnare, .octave=0, .vel=112, .gate=120}, {.step=10, .tone=kSnare, .octave=0, .vel=58, .gate=50}, {.step=0, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=1, .tone=kTambourine, .octave=0, .vel=52, .gate=50}, {.step=2, .tone=kTambourine, .octave=0, .vel=58, .gate=50}, {.step=3, .tone=kTambourine, .octave=0, .vel=52, .gate=50}, {.step=4, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=5, .tone=kTambourine, .octave=0, .vel=52, .gate=50}, {.step=6, .tone=kTambourine, .octave=0, .vel=58, .gate=50}, {.step=7, .tone=kTambourine, .octave=0, .vel=52, .gate=50}, {.step=8, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=9, .tone=kTambourine, .octave=0, .vel=52, .gate=50}, {.step=10, .tone=kTambourine, .octave=0, .vel=58, .gate=50}, {.step=11, .tone=kTambourine, .octave=0, .vel=52, .gate=50}, {.step=12, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=13, .tone=kTambourine, .octave=0, .vel=52, .gate=50}, {.step=14, .tone=kTambourine, .octave=0, .vel=58, .gate=50}, {.step=15, .tone=kTambourine, .octave=0, .vel=52, .gate=50}};
inline constexpr StyleEvent kDC[] = {{.step=2, .tone=kRoot, .octave=0, .vel=84, .gate=kGateStab}, {.step=2, .tone=kThird, .octave=0, .vel=84, .gate=kGateStab}, {.step=2, .tone=kFifth, .octave=0, .vel=84, .gate=kGateStab}, {.step=2, .tone=kSeventh, .octave=0, .vel=84, .gate=kGateStab}, {.step=6, .tone=kRoot, .octave=0, .vel=80, .gate=kGateStab}, {.step=6, .tone=kThird, .octave=0, .vel=80, .gate=kGateStab}, {.step=6, .tone=kFifth, .octave=0, .vel=80, .gate=kGateStab}, {.step=10, .tone=kRoot, .octave=0, .vel=84, .gate=kGateStab}, {.step=10, .tone=kThird, .octave=0, .vel=84, .gate=kGateStab}, {.step=10, .tone=kFifth, .octave=0, .vel=84, .gate=kGateStab}, {.step=10, .tone=kSeventh, .octave=0, .vel=84, .gate=kGateStab}, {.step=14, .tone=kRoot, .octave=0, .vel=80, .gate=kGateStab}, {.step=14, .tone=kThird, .octave=0, .vel=80, .gate=kGateStab}, {.step=14, .tone=kFifth, .octave=0, .vel=80, .gate=kGateStab}};
inline constexpr StylePattern kDP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kDD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSoulBass)}, {.role=TrackRole::kChord1, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kDC)}};
inline constexpr StyleSection kSections[] = {
    {.type=SectionType::kIntro1, .bars=1, .patterns=Span<const StylePattern>(kIn1P)}, {.type=SectionType::kIntro2, .bars=1, .patterns=Span<const StylePattern>(kIn2P)},
    {.type=SectionType::kVarA, .bars=1, .patterns=Span<const StylePattern>(kAP)}, {.type=SectionType::kVarB, .bars=1, .patterns=Span<const StylePattern>(kBP)},
    {.type=SectionType::kVarC, .bars=1, .patterns=Span<const StylePattern>(kCP)}, {.type=SectionType::kVarD, .bars=1, .patterns=Span<const StylePattern>(kDP)},
    {.type=SectionType::kFillA, .bars=1, .patterns=Span<const StylePattern>(kFAP)}, {.type=SectionType::kFillB, .bars=1, .patterns=Span<const StylePattern>(kFBP)}, {.type=SectionType::kFillC, .bars=1, .patterns=Span<const StylePattern>(kFCP)}, {.type=SectionType::kFillD, .bars=1, .patterns=Span<const StylePattern>(kFDP)},
    {.type=SectionType::kEnding1, .bars=1, .patterns=Span<const StylePattern>(kE1P)}, {.type=SectionType::kEnding2, .bars=1, .patterns=Span<const StylePattern>(kE2P)},
};
inline constexpr Style kStyle{.name="motown", .sections=Span<const StyleSection>(kSections)};
}  // namespace motown

}  // namespace styles
}  // namespace arrangrr
