#pragma once

#include "arrangrr/arranger/style_model.hpp"

namespace arrangrr {
namespace styles {


// ---------------------------------------------------------------------------
// "samba": driving surdo kick on the backbeat, busy tamborim 16ths, agogo
// bells, a syncopated root-fifth bass and short percussive stabs.
namespace samba {
inline constexpr StyleEvent kHeldBass[] = {{.step=0, .tone=kRoot, .octave=0, .vel=94, .gate=kGateHeld}};
inline constexpr StyleEvent kSyncBass[] = {{.step=0, .tone=kRoot, .octave=0, .vel=96, .gate=kGate8th}, {.step=4, .tone=kFifth, .octave=-1, .vel=100, .gate=kGate8th}, {.step=6, .tone=kRoot, .octave=0, .vel=84, .gate=kGateStaccato}, {.step=8, .tone=kRoot, .octave=0, .vel=92, .gate=kGate8th}, {.step=12, .tone=kFifth, .octave=-1, .vel=100, .gate=kGate8th}, {.step=14, .tone=kRoot, .octave=0, .vel=84, .gate=kGateStaccato}};
// ---------------------------------------------------------------------------
// Fuller-band roles (ADDITIVE): a string bed, a nylon-guitar cavaquinho comp, a
// bright arpeggio and very rich shaker/guiro/cowbell percussion. Pad at register
// 48, arp at 72. Voices: pad -> Strings, chord2 -> Nylon Guitar, arp -> Harp.
inline constexpr std::int16_t kPadVoice = 48;
inline constexpr std::int16_t kChord2Voice = 24;
inline constexpr std::int16_t kArpVoice = 46;
inline constexpr StyleEvent kPadTriad[] = {{.step=0, .tone=kRoot, .octave=0, .vel=56, .gate=kGateHeld}, {.step=0, .tone=kThird, .octave=0, .vel=54, .gate=kGateHeld}, {.step=0, .tone=kFifth, .octave=0, .vel=56, .gate=kGateHeld}};
inline constexpr StyleEvent kPad7[] = {{.step=0, .tone=kRoot, .octave=0, .vel=58, .gate=kGateHeld}, {.step=0, .tone=kThird, .octave=0, .vel=56, .gate=kGateHeld}, {.step=0, .tone=kFifth, .octave=0, .vel=58, .gate=kGateHeld}, {.step=0, .tone=kSeventh, .octave=0, .vel=52, .gate=kGateHeld}};
inline constexpr StyleEvent kPadRehit[] = {{.step=0, .tone=kRoot, .octave=0, .vel=58, .gate=kGateHalfBar}, {.step=0, .tone=kThird, .octave=0, .vel=56, .gate=kGateHalfBar}, {.step=0, .tone=kFifth, .octave=0, .vel=58, .gate=kGateHalfBar}, {.step=0, .tone=kSeventh, .octave=0, .vel=52, .gate=kGateHalfBar}, {.step=8, .tone=kRoot, .octave=0, .vel=56, .gate=kGateHalfBar}, {.step=8, .tone=kThird, .octave=0, .vel=54, .gate=kGateHalfBar}, {.step=8, .tone=kFifth, .octave=0, .vel=56, .gate=kGateHalfBar}, {.step=8, .tone=kSeventh, .octave=0, .vel=50, .gate=kGateHalfBar}};
inline constexpr StyleEvent kChord2Sync[] = {{.step=3, .tone=kThird, .octave=0, .vel=62, .gate=kGateStaccato}, {.step=3, .tone=kSeventh, .octave=0, .vel=62, .gate=kGateStaccato}, {.step=7, .tone=kThird, .octave=0, .vel=60, .gate=kGateStaccato}, {.step=7, .tone=kFifth, .octave=0, .vel=60, .gate=kGateStaccato}, {.step=11, .tone=kThird, .octave=0, .vel=62, .gate=kGateStaccato}, {.step=11, .tone=kSeventh, .octave=0, .vel=62, .gate=kGateStaccato}, {.step=15, .tone=kFifth, .octave=0, .vel=58, .gate=kGateStaccato}, {.step=15, .tone=kSeventh, .octave=0, .vel=58, .gate=kGateStaccato}};
inline constexpr StyleEvent kChord2Off[] = {{.step=1, .tone=kThird, .octave=0, .vel=60, .gate=kGateStaccato}, {.step=1, .tone=kSeventh, .octave=0, .vel=60, .gate=kGateStaccato}, {.step=3, .tone=kFifth, .octave=0, .vel=58, .gate=kGateStaccato}, {.step=3, .tone=kSeventh, .octave=0, .vel=58, .gate=kGateStaccato}, {.step=7, .tone=kThird, .octave=0, .vel=60, .gate=kGateStaccato}, {.step=7, .tone=kSeventh, .octave=0, .vel=60, .gate=kGateStaccato}, {.step=9, .tone=kFifth, .octave=0, .vel=58, .gate=kGateStaccato}, {.step=9, .tone=kSeventh, .octave=0, .vel=58, .gate=kGateStaccato}, {.step=11, .tone=kThird, .octave=0, .vel=60, .gate=kGateStaccato}, {.step=11, .tone=kSeventh, .octave=0, .vel=60, .gate=kGateStaccato}, {.step=15, .tone=kFifth, .octave=0, .vel=58, .gate=kGateStaccato}, {.step=15, .tone=kSeventh, .octave=0, .vel=58, .gate=kGateStaccato}};
inline constexpr StyleEvent kArp8[] = {{.step=0, .tone=kRoot, .octave=0, .vel=62, .gate=kGateHat}, {.step=2, .tone=kFifth, .octave=0, .vel=56, .gate=kGateHat}, {.step=4, .tone=kThird, .octave=0, .vel=60, .gate=kGateHat}, {.step=6, .tone=kSeventh, .octave=0, .vel=56, .gate=kGateHat}, {.step=8, .tone=kRoot, .octave=1, .vel=62, .gate=kGateHat}, {.step=10, .tone=kFifth, .octave=0, .vel=56, .gate=kGateHat}, {.step=12, .tone=kThird, .octave=1, .vel=60, .gate=kGateHat}, {.step=14, .tone=kSeventh, .octave=0, .vel=56, .gate=kGateHat}};
inline constexpr StyleEvent kPercShake[] = {{.step=0, .tone=kMaracas, .octave=0, .vel=56, .gate=kGateHat}, {.step=2, .tone=kMaracas, .octave=0, .vel=46, .gate=kGateHat}, {.step=4, .tone=kMaracas, .octave=0, .vel=56, .gate=kGateHat}, {.step=6, .tone=kMaracas, .octave=0, .vel=46, .gate=kGateHat}, {.step=8, .tone=kMaracas, .octave=0, .vel=56, .gate=kGateHat}, {.step=10, .tone=kMaracas, .octave=0, .vel=46, .gate=kGateHat}, {.step=12, .tone=kMaracas, .octave=0, .vel=56, .gate=kGateHat}, {.step=14, .tone=kMaracas, .octave=0, .vel=46, .gate=kGateHat}};
inline constexpr StyleEvent kPercRich[] = {{.step=0, .tone=kShortGuiro, .octave=0, .vel=62, .gate=kGateHat}, {.step=4, .tone=kShortGuiro, .octave=0, .vel=58, .gate=kGateHat}, {.step=8, .tone=kShortGuiro, .octave=0, .vel=62, .gate=kGateHat}, {.step=12, .tone=kShortGuiro, .octave=0, .vel=58, .gate=kGateHat}, {.step=2, .tone=kCowbell, .octave=0, .vel=54, .gate=kGateHat}, {.step=6, .tone=kCowbell, .octave=0, .vel=50, .gate=kGateHat}, {.step=10, .tone=kCowbell, .octave=0, .vel=54, .gate=kGateHat}, {.step=14, .tone=kCowbell, .octave=0, .vel=50, .gate=kGateHat}};
inline constexpr StyleEvent kIn1D[] = {{.step=8, .tone=kHiAgogo, .octave=0, .vel=70, .gate=50}, {.step=10, .tone=kLoAgogo, .octave=0, .vel=64, .gate=50}, {.step=12, .tone=kHiAgogo, .octave=0, .vel=76, .gate=50}, {.step=14, .tone=kLoAgogo, .octave=0, .vel=80, .gate=50}};
inline constexpr StylePattern kIn1P[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kIn1D)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kHeldBass)}};
inline constexpr StyleEvent kIn2D[] = {{.step=4, .tone=kKick, .octave=0, .vel=100, .gate=50}, {.step=12, .tone=kKick, .octave=0, .vel=104, .gate=50}, {.step=0, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=2, .tone=kTambourine, .octave=0, .vel=54, .gate=50}, {.step=4, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=6, .tone=kTambourine, .octave=0, .vel=54, .gate=50}, {.step=8, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=10, .tone=kTambourine, .octave=0, .vel=54, .gate=50}, {.step=12, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=14, .tone=kTambourine, .octave=0, .vel=54, .gate=50}};
// Cavaquinho/guitar chord stabs on the offbeats become ONE gesture event each
// (D42): gesture::expand ignores the authored tone and brushes the whole live
// chord low->high (kStrumUp) / high->low (kStrumDown), adapting to triad vs 7th.
inline constexpr StyleEvent kIn2C[] = {{.step=2, .tone=kRoot, .octave=0, .vel=76, .gate=kGateStaccato, .gesture=ChordGesture::kStrumUp}, {.step=10, .tone=kRoot, .octave=0, .vel=74, .gate=kGateStaccato, .gesture=ChordGesture::kStrumDown}};
inline constexpr StylePattern kIn2P[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kIn2D)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSyncBass)}, {.role=TrackRole::kChord1, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kIn2C)}, {.role=TrackRole::kPad, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kPadTriad), .gm_program=kPadVoice, .voicing=VoicingPolicy::kLead}};
inline constexpr StyleEvent kAD[] = {
    {.step=4, .tone=kKick, .octave=0, .vel=108, .gate=50}, {.step=12, .tone=kKick, .octave=0, .vel=112, .gate=50}, {.step=0, .tone=kKick, .octave=0, .vel=76, .gate=50}, {.step=8, .tone=kKick, .octave=0, .vel=76, .gate=50},
    {.step=0, .tone=kTambourine, .octave=0, .vel=64, .gate=50}, {.step=1, .tone=kTambourine, .octave=0, .vel=48, .gate=50}, {.step=2, .tone=kTambourine, .octave=0, .vel=58, .gate=50}, {.step=3, .tone=kTambourine, .octave=0, .vel=48, .gate=50}, {.step=4, .tone=kTambourine, .octave=0, .vel=64, .gate=50}, {.step=5, .tone=kTambourine, .octave=0, .vel=48, .gate=50}, {.step=6, .tone=kTambourine, .octave=0, .vel=58, .gate=50}, {.step=7, .tone=kTambourine, .octave=0, .vel=48, .gate=50}, {.step=8, .tone=kTambourine, .octave=0, .vel=64, .gate=50}, {.step=9, .tone=kTambourine, .octave=0, .vel=48, .gate=50}, {.step=10, .tone=kTambourine, .octave=0, .vel=58, .gate=50}, {.step=11, .tone=kTambourine, .octave=0, .vel=48, .gate=50}, {.step=12, .tone=kTambourine, .octave=0, .vel=64, .gate=50}, {.step=13, .tone=kTambourine, .octave=0, .vel=48, .gate=50}, {.step=14, .tone=kTambourine, .octave=0, .vel=58, .gate=50}, {.step=15, .tone=kTambourine, .octave=0, .vel=48, .gate=50},
    {.step=0, .tone=kHiAgogo, .octave=0, .vel=72, .gate=50}, {.step=3, .tone=kLoAgogo, .octave=0, .vel=64, .gate=50}, {.step=6, .tone=kHiAgogo, .octave=0, .vel=68, .gate=50}, {.step=8, .tone=kHiAgogo, .octave=0, .vel=72, .gate=50}, {.step=11, .tone=kLoAgogo, .octave=0, .vel=64, .gate=50}, {.step=14, .tone=kHiAgogo, .octave=0, .vel=68, .gate=50},
};
inline constexpr StyleEvent kAC[] = {{.step=2, .tone=kRoot, .octave=0, .vel=80, .gate=kGateStaccato, .gesture=ChordGesture::kStrumUp}, {.step=6, .tone=kRoot, .octave=0, .vel=76, .gate=kGateStaccato, .gesture=ChordGesture::kStrumDown}, {.step=10, .tone=kRoot, .octave=0, .vel=80, .gate=kGateStaccato, .gesture=ChordGesture::kStrumUp}, {.step=14, .tone=kRoot, .octave=0, .vel=76, .gate=kGateStaccato, .gesture=ChordGesture::kStrumDown}};
inline constexpr StylePattern kAP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kAD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSyncBass)}, {.role=TrackRole::kChord1, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kAC)}, {.role=TrackRole::kPad, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kPadTriad), .gm_program=kPadVoice, .voicing=VoicingPolicy::kLead}, {.role=TrackRole::kChord2, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kChord2Sync), .gm_program=kChord2Voice}};
inline constexpr StyleEvent kBD[] = {
    {.step=4, .tone=kKick, .octave=0, .vel=112, .gate=50}, {.step=12, .tone=kKick, .octave=0, .vel=116, .gate=50}, {.step=0, .tone=kKick, .octave=0, .vel=84, .gate=50}, {.step=8, .tone=kKick, .octave=0, .vel=84, .gate=50}, {.step=7, .tone=kKick, .octave=0, .vel=70, .gate=50}, {.step=15, .tone=kKick, .octave=0, .vel=70, .gate=50},
    {.step=0, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=1, .tone=kTambourine, .octave=0, .vel=50, .gate=50}, {.step=2, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=3, .tone=kTambourine, .octave=0, .vel=50, .gate=50}, {.step=4, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=5, .tone=kTambourine, .octave=0, .vel=50, .gate=50}, {.step=6, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=7, .tone=kTambourine, .octave=0, .vel=50, .gate=50}, {.step=8, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=9, .tone=kTambourine, .octave=0, .vel=50, .gate=50}, {.step=10, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=11, .tone=kTambourine, .octave=0, .vel=50, .gate=50}, {.step=12, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=13, .tone=kTambourine, .octave=0, .vel=50, .gate=50}, {.step=14, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=15, .tone=kTambourine, .octave=0, .vel=50, .gate=50},
    {.step=2, .tone=kOpenHiConga, .octave=0, .vel=70, .gate=50}, {.step=6, .tone=kLoConga, .octave=0, .vel=72, .gate=50}, {.step=10, .tone=kOpenHiConga, .octave=0, .vel=70, .gate=50}, {.step=14, .tone=kLoConga, .octave=0, .vel=74, .gate=50},
};
inline constexpr StyleEvent kBC[] = {{.step=0, .tone=kRoot, .octave=0, .vel=82, .gate=kGateStaccato, .gesture=ChordGesture::kStrumUp}, {.step=3, .tone=kRoot, .octave=0, .vel=76, .gate=kGateStaccato, .gesture=ChordGesture::kStrumDown}, {.step=6, .tone=kRoot, .octave=0, .vel=80, .gate=kGateStaccato, .gesture=ChordGesture::kStrumUp}, {.step=10, .tone=kRoot, .octave=0, .vel=80, .gate=kGateStaccato, .gesture=ChordGesture::kStrumDown}, {.step=13, .tone=kRoot, .octave=0, .vel=76, .gate=kGateStaccato, .gesture=ChordGesture::kStrumUp}, {.step=14, .tone=kRoot, .octave=0, .vel=78, .gate=kGateStaccato, .gesture=ChordGesture::kStrumDown}};
inline constexpr StylePattern kBP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kBD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSyncBass)}, {.role=TrackRole::kChord1, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kBC)}, {.role=TrackRole::kPad, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kPadTriad), .gm_program=kPadVoice, .voicing=VoicingPolicy::kLead}, {.role=TrackRole::kChord2, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kChord2Sync), .gm_program=kChord2Voice}, {.role=TrackRole::kPerc, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kPercShake)}};
inline constexpr StyleEvent kFAD[] = {{.step=0, .tone=kKick, .octave=0, .vel=100, .gate=50}, {.step=4, .tone=kTomHi, .octave=0, .vel=90, .gate=100}, {.step=6, .tone=kTomHi, .octave=0, .vel=86, .gate=100}, {.step=8, .tone=kTomMid, .octave=0, .vel=94, .gate=100}, {.step=10, .tone=kTomMid, .octave=0, .vel=90, .gate=100}, {.step=12, .tone=kTomLow, .octave=0, .vel=100, .gate=100}, {.step=14, .tone=kTomFloor, .octave=0, .vel=106, .gate=100}};
inline constexpr StyleEvent kFBD[] = {{.step=0, .tone=kTomHi, .octave=0, .vel=90, .gate=100}, {.step=2, .tone=kTomHi, .octave=0, .vel=86, .gate=100}, {.step=4, .tone=kTomMid, .octave=0, .vel=94, .gate=100}, {.step=6, .tone=kTomMid, .octave=0, .vel=90, .gate=100}, {.step=8, .tone=kTomLow, .octave=0, .vel=98, .gate=100}, {.step=10, .tone=kTomLow, .octave=0, .vel=94, .gate=100}, {.step=12, .tone=kTomFloor, .octave=0, .vel=104, .gate=100}, {.step=14, .tone=kTomFloor, .octave=0, .vel=108, .gate=100}};
inline constexpr StyleEvent kFCD[] = {{.step=0, .tone=kOpenHiConga, .octave=0, .vel=88, .gate=50}, {.step=2, .tone=kLoConga, .octave=0, .vel=84, .gate=50}, {.step=4, .tone=kOpenHiConga, .octave=0, .vel=90, .gate=50}, {.step=6, .tone=kLoConga, .octave=0, .vel=86, .gate=50}, {.step=8, .tone=kTomHi, .octave=0, .vel=96, .gate=50}, {.step=10, .tone=kTomMid, .octave=0, .vel=100, .gate=50}, {.step=12, .tone=kTomLow, .octave=0, .vel=104, .gate=50}, {.step=14, .tone=kTomFloor, .octave=0, .vel=110, .gate=50}};
inline constexpr StyleEvent kFDD[] = {{.step=0, .tone=kTomHi, .octave=0, .vel=90, .gate=50}, {.step=1, .tone=kTomHi, .octave=0, .vel=86, .gate=50}, {.step=2, .tone=kTomMid, .octave=0, .vel=92, .gate=50}, {.step=3, .tone=kTomMid, .octave=0, .vel=88, .gate=50}, {.step=4, .tone=kTomLow, .octave=0, .vel=96, .gate=50}, {.step=5, .tone=kTomLow, .octave=0, .vel=92, .gate=50}, {.step=6, .tone=kTomFloor, .octave=0, .vel=100, .gate=50}, {.step=7, .tone=kTomFloor, .octave=0, .vel=96, .gate=50}, {.step=8, .tone=kSnare, .octave=0, .vel=102, .gate=50}, {.step=9, .tone=kSnare, .octave=0, .vel=98, .gate=50}, {.step=10, .tone=kSnare, .octave=0, .vel=104, .gate=50}, {.step=11, .tone=kSnare, .octave=0, .vel=100, .gate=50}, {.step=12, .tone=kSnare, .octave=0, .vel=108, .gate=50}, {.step=13, .tone=kSnare, .octave=0, .vel=112, .gate=50}, {.step=14, .tone=kSnare, .octave=0, .vel=116, .gate=50}, {.step=15, .tone=kCrash, .octave=0, .vel=120, .gate=kGate8th}};
inline constexpr StylePattern kFAP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kFAD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSyncBass)}};
inline constexpr StylePattern kFBP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kFBD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSyncBass)}};
inline constexpr StylePattern kFCP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kFCD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSyncBass)}};
inline constexpr StylePattern kFDP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kFDD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSyncBass)}, {.role=TrackRole::kPerc, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kPercRich)}};
inline constexpr StyleEvent kE1D[] = {{.step=0, .tone=kCrash, .octave=0, .vel=100, .gate=kGateHalfBar}, {.step=0, .tone=kKick, .octave=0, .vel=104, .gate=50}, {.step=8, .tone=kKick, .octave=0, .vel=96, .gate=50}};
inline constexpr StyleEvent kE1B[] = {{.step=0, .tone=kRoot, .octave=0, .vel=100, .gate=kGateHeld}};
inline constexpr StyleEvent kE1C[] = {{.step=0, .tone=kRoot, .octave=0, .vel=84, .gate=kGateHeld}, {.step=0, .tone=kThird, .octave=0, .vel=84, .gate=kGateHeld}, {.step=0, .tone=kFifth, .octave=0, .vel=84, .gate=kGateHeld}, {.step=0, .tone=kSeventh, .octave=0, .vel=84, .gate=kGateHeld}};
inline constexpr StylePattern kE1P[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kE1D)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kE1B)}, {.role=TrackRole::kChord1, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kE1C)}, {.role=TrackRole::kPad, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kPad7), .gm_program=kPadVoice, .voicing=VoicingPolicy::kLead}};
inline constexpr StyleEvent kE2D[] = {{.step=0, .tone=kCrash, .octave=0, .vel=110, .gate=kGateHeld}, {.step=0, .tone=kKick, .octave=0, .vel=108, .gate=50}, {.step=4, .tone=kKick, .octave=0, .vel=100, .gate=50}, {.step=8, .tone=kKick, .octave=0, .vel=104, .gate=50}, {.step=12, .tone=kKick, .octave=0, .vel=100, .gate=50}};
inline constexpr StyleEvent kE2B[] = {{.step=0, .tone=kRoot, .octave=-1, .vel=104, .gate=kGateHeld}, {.step=0, .tone=kRoot, .octave=0, .vel=94, .gate=kGateHeld}};
inline constexpr StyleEvent kE2C[] = {{.step=0, .tone=kRoot, .octave=0, .vel=86, .gate=kGateHeld}, {.step=0, .tone=kThird, .octave=0, .vel=86, .gate=kGateHeld}, {.step=0, .tone=kFifth, .octave=0, .vel=86, .gate=kGateHeld}, {.step=0, .tone=kSeventh, .octave=0, .vel=86, .gate=kGateHeld}};
inline constexpr StylePattern kE2P[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kE2D)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kE2B)}, {.role=TrackRole::kChord1, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kE2C)}, {.role=TrackRole::kPad, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kPad7), .gm_program=kPadVoice, .voicing=VoicingPolicy::kLead}};
// varC: batucada breakdown — surdo backbeat and agogo clave only, tamborim dropped.
inline constexpr StyleEvent kCD[] = {{.step=4, .tone=kKick, .octave=0, .vel=108, .gate=50}, {.step=12, .tone=kKick, .octave=0, .vel=112, .gate=50}, {.step=0, .tone=kHiAgogo, .octave=0, .vel=72, .gate=50}, {.step=3, .tone=kLoAgogo, .octave=0, .vel=64, .gate=50}, {.step=6, .tone=kHiAgogo, .octave=0, .vel=68, .gate=50}, {.step=8, .tone=kHiAgogo, .octave=0, .vel=72, .gate=50}, {.step=11, .tone=kLoAgogo, .octave=0, .vel=64, .gate=50}, {.step=14, .tone=kHiAgogo, .octave=0, .vel=68, .gate=50}};
inline constexpr StyleEvent kCC[] = {{.step=2, .tone=kRoot, .octave=0, .vel=78, .gate=kGateStaccato, .gesture=ChordGesture::kStrumUp}, {.step=10, .tone=kRoot, .octave=0, .vel=76, .gate=kGateStaccato, .gesture=ChordGesture::kStrumDown}};
inline constexpr StylePattern kCP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kCD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSyncBass)}, {.role=TrackRole::kChord1, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kCC)}, {.role=TrackRole::kPad, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kPadRehit), .gm_program=kPadVoice, .voicing=VoicingPolicy::kLead}, {.role=TrackRole::kChord2, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kChord2Off), .gm_program=kChord2Voice}, {.role=TrackRole::kArp, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kArp8), .gm_program=kArpVoice}};
// varD: peak escola — full surdo, 16th tamborim, congas and agogo, full 7th stabs.
inline constexpr StyleEvent kDD[] = {{.step=4, .tone=kKick, .octave=0, .vel=114, .gate=50}, {.step=12, .tone=kKick, .octave=0, .vel=118, .gate=50}, {.step=0, .tone=kKick, .octave=0, .vel=84, .gate=50}, {.step=8, .tone=kKick, .octave=0, .vel=84, .gate=50}, {.step=7, .tone=kKick, .octave=0, .vel=70, .gate=50}, {.step=15, .tone=kKick, .octave=0, .vel=70, .gate=50}, {.step=0, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=1, .tone=kTambourine, .octave=0, .vel=50, .gate=50}, {.step=2, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=3, .tone=kTambourine, .octave=0, .vel=50, .gate=50}, {.step=4, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=5, .tone=kTambourine, .octave=0, .vel=50, .gate=50}, {.step=6, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=7, .tone=kTambourine, .octave=0, .vel=50, .gate=50}, {.step=8, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=9, .tone=kTambourine, .octave=0, .vel=50, .gate=50}, {.step=10, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=11, .tone=kTambourine, .octave=0, .vel=50, .gate=50}, {.step=12, .tone=kTambourine, .octave=0, .vel=66, .gate=50}, {.step=13, .tone=kTambourine, .octave=0, .vel=50, .gate=50}, {.step=14, .tone=kTambourine, .octave=0, .vel=60, .gate=50}, {.step=15, .tone=kTambourine, .octave=0, .vel=50, .gate=50}, {.step=2, .tone=kOpenHiConga, .octave=0, .vel=72, .gate=50}, {.step=6, .tone=kLoConga, .octave=0, .vel=74, .gate=50}, {.step=10, .tone=kOpenHiConga, .octave=0, .vel=72, .gate=50}, {.step=14, .tone=kLoConga, .octave=0, .vel=76, .gate=50}, {.step=0, .tone=kHiAgogo, .octave=0, .vel=74, .gate=50}, {.step=8, .tone=kHiAgogo, .octave=0, .vel=74, .gate=50}};
inline constexpr StyleEvent kDC[] = {{.step=0, .tone=kRoot, .octave=0, .vel=84, .gate=kGateStaccato, .gesture=ChordGesture::kStrumUp}, {.step=6, .tone=kRoot, .octave=0, .vel=80, .gate=kGateStaccato, .gesture=ChordGesture::kStrumDown}, {.step=10, .tone=kRoot, .octave=0, .vel=82, .gate=kGateStaccato, .gesture=ChordGesture::kStrumUp}, {.step=14, .tone=kRoot, .octave=0, .vel=80, .gate=kGateStaccato, .gesture=ChordGesture::kStrumDown}};
inline constexpr StylePattern kDP[] = {{.role=TrackRole::kDrums, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kDD)}, {.role=TrackRole::kBass, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kSyncBass)}, {.role=TrackRole::kChord1, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kDC)}, {.role=TrackRole::kPad, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kPadRehit), .gm_program=kPadVoice, .voicing=VoicingPolicy::kLead}, {.role=TrackRole::kChord2, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kChord2Off), .gm_program=kChord2Voice}, {.role=TrackRole::kArp, .policy=RolePolicy::kChordTone, .events=Span<const StyleEvent>(kArp8), .gm_program=kArpVoice}, {.role=TrackRole::kPerc, .policy=RolePolicy::kFixed, .events=Span<const StyleEvent>(kPercRich)}};
inline constexpr StyleSection kSections[] = {
    {.type=SectionType::kIntro1, .bars=1, .patterns=Span<const StylePattern>(kIn1P)}, {.type=SectionType::kIntro2, .bars=1, .patterns=Span<const StylePattern>(kIn2P)},
    {.type=SectionType::kVarA, .bars=1, .patterns=Span<const StylePattern>(kAP)}, {.type=SectionType::kVarB, .bars=1, .patterns=Span<const StylePattern>(kBP)},
    {.type=SectionType::kVarC, .bars=1, .patterns=Span<const StylePattern>(kCP)}, {.type=SectionType::kVarD, .bars=1, .patterns=Span<const StylePattern>(kDP)},
    {.type=SectionType::kFillA, .bars=1, .patterns=Span<const StylePattern>(kFAP)}, {.type=SectionType::kFillB, .bars=1, .patterns=Span<const StylePattern>(kFBP)}, {.type=SectionType::kFillC, .bars=1, .patterns=Span<const StylePattern>(kFCP)}, {.type=SectionType::kFillD, .bars=1, .patterns=Span<const StylePattern>(kFDP)},
    {.type=SectionType::kEnding1, .bars=1, .patterns=Span<const StylePattern>(kE1P)}, {.type=SectionType::kEnding2, .bars=1, .patterns=Span<const StylePattern>(kE2P)},
};
inline constexpr Style kStyle{.name="samba", .sections=Span<const StyleSection>(kSections), .tempo=10400};
}  // namespace samba

}  // namespace styles
}  // namespace arrangrr
